name: "Updatecli: Dependency Management"

on:
  schedule:
    # Runs at 06 PM UTC
    - cron: '0 18 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

jobs:
  updatecli:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      contents: write
      issues: write
      id-token: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: 'stable'

      - name: Install Updatecli
        uses: updatecli/updatecli-action@41b9c8d707830a9daebaeaa84c1b62d60b779564 # v3.6.0

      - name: Load Secrets from Vault
        id: secrets
        uses: rancher/eio-workflow-actions/secrets@main
        with:
          secrets: |
            RENOVATE_RANCHER_APP_ID=renovate-rancher-app-id
            RENOVATE_RANCHER_APP_PRIVATE_KEY=renovate-rancher-app-private-key

      - name: Generate App Token
        id: app-token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        with:
          app-id: ${{ steps.secrets.outputs.RENOVATE_RANCHER_APP_ID }}
          private-key: ${{ steps.secrets.outputs.RENOVATE_RANCHER_APP_PRIVATE_KEY }}

      - name: Delete leftover UpdateCLI branches
        run: |
          gh pr list \
            --search "is:closed is:pr head:updatecli_" \
            --json headRefName \
            --jq ".[].headRefName" | sort -u > closed_prs_branches.txt
          gh pr list \
            --search "is:open is:pr head:updatecli_" \
            --json headRefName \
            --jq ".[].headRefName" | sort -u > open_prs_branches.txt
          for branch in $(comm -23 closed_prs_branches.txt open_prs_branches.txt); do
            if (git ls-remote --exit-code --heads origin "$branch"); then
              echo "Deleting leftover UpdateCLI branch - $branch";
              git push origin --delete "$branch";
            fi
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Apply Updatecli
        # Never use '--debug' option, because it might leak the access tokens.
        run: "updatecli pipeline apply --clean --config ./updatecli/updatecli.d/ --values ./updatecli/values.yaml"
        env:
          UPDATECLI_GITHUB_ACTOR: renovate-rancher[bot]
          UPDATECLI_GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
